apiVersion: apps/v1
kind: Deployment
metadata:
  name: statusView
  labels:
    app: statusView
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statusView
  template:
    metadata:
      labels:
        app: statusView
    spec:
      containers:
        - name: statusView
          image: admin20.azurecr.io/statusView:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5